// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjXr9Ve1kQAisYr2vHilqQnYUZuyZ2me0',
    appId: '1:927381146865:web:938d12b5192a21d97bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    authDomain: 'loopin-mvp.firebaseapp.com',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    measurementId: 'G-7T7PE4DTVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-7FlMae9dEsytDTOmxwZwQqWoMFpn2M',
    appId: '1:927381146865:android:d1d88c79ffe862667bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    storageBucket: 'loopin-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAM5uPboQgnPnoYs-Le1gNpKNSf5N4r4',
    appId: '1:927381146865:ios:71bd2cb691f2eb217bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    iosBundleId: 'com.example.loopinMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAM5uPboQgnPnoYs-Le1gNpKNSf5N4r4',
    appId: '1:927381146865:ios:71bd2cb691f2eb217bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    iosBundleId: 'com.example.loopinMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjXr9Ve1kQAisYr2vHilqQnYUZuyZ2me0',
    appId: '1:927381146865:web:b777ad79c120bb007bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    authDomain: 'loopin-mvp.firebaseapp.com',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    measurementId: 'G-RNBD8P1G7D',
  );
}
