// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase 설정을 플랫폼별로 분기하여 제공합니다.
/// Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform); 형태로 사용
class DefaultFirebaseOptions {
  /// 현재 플랫폼에 맞는 FirebaseOptions 반환
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux는 Firebase 설정이 되어 있지 않습니다. FlutterFire CLI로 재설정이 필요합니다.',
        );
      default:
        throw UnsupportedError('지원되지 않는 플랫폼입니다.');
    }
  }

  /// 🔹 Web Firebase 설정
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjXr9Ve1kQAisYr2vHilqQnYUZuyZ2me0',
    appId: '1:927381146865:web:938d12b5192a21d97bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    authDomain: 'loopin-mvp.firebaseapp.com',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    measurementId: 'G-7T7PE4DTVQ',
  );

  /// 🔹 Android Firebase 설정
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-7FlMae9dEsytDTOmxwZwQqWoMFpn2M',
    appId: '1:927381146865:android:d1d88c79ffe862667bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    storageBucket: 'loopin-mvp.firebasestorage.app',
  );

  /// 🔹 iOS Firebase 설정
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAM5uPboQgnPnoYs-Le1gNpKNSf5N4r4',
    appId: '1:927381146865:ios:71bd2cb691f2eb217bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    iosBundleId: 'com.example.loopinMvp',
  );

  /// 🔹 macOS Firebase 설정 (iOS와 동일하게 구성됨)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAM5uPboQgnPnoYs-Le1gNpKNSf5N4r4',
    appId: '1:927381146865:ios:71bd2cb691f2eb217bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    iosBundleId: 'com.example.loopinMvp',
  );

  /// 🔹 Windows Firebase 설정 (웹 설정 재사용)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjXr9Ve1kQAisYr2vHilqQnYUZuyZ2me0',
    appId: '1:927381146865:web:b777ad79c120bb007bad50',
    messagingSenderId: '927381146865',
    projectId: 'loopin-mvp',
    authDomain: 'loopin-mvp.firebaseapp.com',
    storageBucket: 'loopin-mvp.firebasestorage.app',
    measurementId: 'G-RNBD8P1G7D',
  );
}
